### ISSUE TITLE
Error when detect attack

### ISSUE THREAD

**Issue by decioseo** [WiPi-Hunter/PiKarma#1]
Hello I saw you demonstration in defcon26 and we are teaching our Cyber students about you tool.
 But we are having this error into kali linux

File "Pikarma,py" line 153 <Module>
blacklist =pp_analysis(info_list,pp,pikarma_method)
File "Pikarma,py" line 98, in pp_analysis
pp_deauth(blacklist)
File "Pikarma,py" line 125, in pp_deauth
channel = find_channel(clist, target)
File "Pikarma,py" line 112, in find_channel
retun channel
UnboundLocalError:local variable 'channel' referenced before assignment

Could You Help Us?

**Comment by besimaltnok** [comment]
Hi, Thank you for support, I solve this problem for you.
I added global channel variable.
clone again from repo and use without error. Thanks again. as soon as, I will new update with new feature. Follow me :)

**Comment by decioseo** [comment]
Thank you I will test again, by the way I will try to integrate Pikarma, Pidense and PiSavar logs into graylog, did you tried something like this?

Regards,

Decio Seo

**Comment by besimaltnok** [comment]
I didn't try, but if you need help, I'm always here for you :)
